slogan: "好好学习 天天向上"

theme: false
inverse: false

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    icon: "fa fa-user"

links:
  - title: "Puzzle4fun"
    url: https://github.com/puzzlefun
    intro: "My Github account."
    icon: "fa fa-github"
  - title: "My LinkedIn"
    url: https://cn.linkedin.com/in/carl-liu-337796a2
    intro: "My Linkin account."
    icon: "fa fa-linkedin"
  - title: "新浪微博"
    url: http://weibo.com/u/3283459547
    intro: "我的新浪微博."
    icon: "fa fa-weibo"

widgets:
- search
- category
- tagcloud
- recent_posts  
- links
- google_adsence

rss: atom.xml
fancybox: true
favicon: favicon.png
duoshuo_shortname: puzzlefun

# Analytics
google_analytics:
  enable: true
  siteid: UA-69869444-1
baidu_tongji:
  enable: true
  siteid: e358945bd22b2347e568dd59e2f62845

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# share widgets
bdshare: true
jiathis: false

